### ISSUE TITLE
Text: missing data labels

### ISSUE THREAD

**Issue by ahmedmagdiosman** [zhengliz/natural-adversary#1]
Hello there,

First, thanks for sharing your code!

I'm trying to run `train_baseline` for text but I'm getting this error:
````
Traceback (most recent call last):
  File "train_baseline.py", line 66, in <module>
    corpus_train = SNLIDataset(train=True, vocab_size=11004, lvt=False, path=args.data_path)
  File "/home/aosman/02_fields/adversarial/natural-adversary/text/utils.py", line 276, in __init__
    self.train_data = self.tokenize(self.train_path)
  File "/home/aosman/02_fields/adversarial/natural-adversary/text/utils.py", line 336, in tokenize
    label = self.labels[tokens[0]]
KeyError: 'A person on a horse jumps over a broken down airplane .'
````

 it seems that the labels are missing from the text files (`train.txt` and `test.txt`). Would you be kind to provide them or let me know where to get them? 

Thanks!

**Comment by dDua** [comment]
Hi 

Thanks for reporting this. The data folder on google drive has now been updated with the files for baseline classifier in the data/classifier folder (please see readme) . For training the inverter you would still need to use the train.txt and test.txt in the data folder itself.

**Comment by ahmedmagdiosman** [comment]
Thanks for updating the data. That fixed this problem. However, it seems that there are still some files missing:

````
Number of sentences dropped from data/classifier/train.txt: 448221 out of 549367 total
Number of sentences dropped from data/classifier/test.txt: 8288 out of 9824 total
Traceback (most recent call last):
  File "train_baseline.py", line 79, in <module>
    baseline_model = Baseline_Embeddings(100,maxlen=args.maxlen, gpu=args.cuda, vocab_size=11004)
  File "/home/aosman/02_fields/adversarial/natural-adversary/text/models.py", line 809, in __init__
    embeddings_mat = load_embeddings()
  File "/home/aosman/02_fields/adversarial/natural-adversary/text/utils.py", line 392, in load_embeddings
    vocab = pkl.load(open(vocab_path))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ddua/data/snli/snli_lm/vocab_41578.pkl'
````
I can find ``vocab_11004.pkl`` not ``vocab_41578.pkl``.
Thanks again for your help.

**Comment by ahmedmagdiosman** [comment]
@dDua Hello there, could kindly let me know if that's a missing file or do I need to generate them myself?

Thanks again.

**Comment by dDua** [comment]
Hey,

I fixed all the file issues in the code and the shared data drive. Please sync all the changes and try again. Let me know if you still face any issues.

Thanks!

**Comment by ahmedmagdiosman** [comment]
@dDua 
Thanks again. 
I pulled the new code and data changes.
I'm facing another error now related with the embeddings file and pytorch's FloatTensor constructor
````
Traceback (most recent call last):
  File "train_baseline.py", line 81, in <module>
    baseline_model = Baseline_Embeddings(100, vocab_size=args.vocab_size)
  File "/home/aosman/02_fields/adversarial/natural-adversary/text/models.py", line 809, in __init__
    embeddings_mat = load_embeddings()
  File "/home/aosman/02_fields/adversarial/natural-adversary/text/utils.py", line 393, in load_embeddings
    embeddings[1].copy_(torch.FloatTensor(map(float,open(file_path).read().split('\n')[0].strip().split(" ")[1:])))
TypeError: torch.FloatTensor constructor received an invalid combination of arguments - got (map), but expected one of:
 * no arguments
 * (int ...)
      didn't match because some of the arguments have invalid types: (map)
 * (torch.FloatTensor viewed_tensor)
      didn't match because some of the arguments have invalid types: (map)
 * (torch.Size size)
      didn't match because some of the arguments have invalid types: (map)
 * (torch.FloatStorage data)
      didn't match because some of the arguments have invalid types: (map)
 * (Sequence data)
      didn't match because some of the arguments have invalid types: (map)
````
**Edit**: Nevermind, I fixed the issue(s). For anyone else struggling, this was was a python2 vs python3 issue since python3 returns a map iterator rather than a list. So, just use list() on the map() output.

However, I got another error after this which was very ambiguous:

````
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518244507981/work/torch/lib/THC/generated/../generic/THCTensorMathReduce.cu line=18 error=59 : device-side assert triggered
````

The cause was a mismatch between the corpus class vocab and the embedding (since the corpus class adds 4 more "words"). 
To fix it, just subtract 4 from the corpus initialization:
````
corpus_train = SNLIDataset(train=True, vocab_size=args.vocab_size-4, path=args.data_path)
corpus_test = SNLIDataset(train=False, vocab_size=args.vocab_size-4, path=args.data_path)

````
Thanks again for sharing your code!
